version: "3.9"
services:
  pair-programmer-db:
    image: postgres
    restart: always
    container_name: pair-programmer-db
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
